# This package contains options shared by all MediaPipe Audio Tasks for Web.

load("//mediapipe/framework/port:build_config.bzl", "mediapipe_ts_declaration")

package(default_visibility = ["//mediapipe/tasks:internal"])

mediapipe_ts_declaration(
    name = "audio_task_options",
    srcs = ["audio_task_options.d.ts"],
    deps = [
        "//mediapipe/tasks/web/core",
    ],
)
