// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mediapipe/gpu/copy_calculator.proto

package mediapipe;

public final class CopyCalculator {
  private CopyCalculator() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(mediapipe.CopyCalculator.CopyCalculatorOptions.ext);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CopyCalculatorOptionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mediapipe.CopyCalculatorOptions)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .mediapipe.CopyCalculatorOptions.Rotation rotation = 1 [default = NONE];</code>
     */
    boolean hasRotation();
    /**
     * <code>optional .mediapipe.CopyCalculatorOptions.Rotation rotation = 1 [default = NONE];</code>
     */
    mediapipe.CopyCalculator.CopyCalculatorOptions.Rotation getRotation();
  }
  /**
   * Protobuf type {@code mediapipe.CopyCalculatorOptions}
   */
  public  static final class CopyCalculatorOptions extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mediapipe.CopyCalculatorOptions)
      CopyCalculatorOptionsOrBuilder {
    // Use CopyCalculatorOptions.newBuilder() to construct.
    private CopyCalculatorOptions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CopyCalculatorOptions() {
      rotation_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CopyCalculatorOptions(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              mediapipe.CopyCalculator.CopyCalculatorOptions.Rotation value = mediapipe.CopyCalculator.CopyCalculatorOptions.Rotation.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                rotation_ = rawValue;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mediapipe.CopyCalculator.internal_static_mediapipe_CopyCalculatorOptions_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mediapipe.CopyCalculator.internal_static_mediapipe_CopyCalculatorOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mediapipe.CopyCalculator.CopyCalculatorOptions.class, mediapipe.CopyCalculator.CopyCalculatorOptions.Builder.class);
    }

    /**
     * Protobuf enum {@code mediapipe.CopyCalculatorOptions.Rotation}
     */
    public enum Rotation
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NONE = 0;</code>
       */
      NONE(0),
      /**
       * <pre>
       * rotate 90 degrees counterclockwise
       * </pre>
       *
       * <code>CCW = 1;</code>
       */
      CCW(1),
      /**
       * <pre>
       * hack to rectify convfloat
       * </pre>
       *
       * <code>CCW_FLIP = 2;</code>
       */
      CCW_FLIP(2),
      ;

      /**
       * <code>NONE = 0;</code>
       */
      public static final int NONE_VALUE = 0;
      /**
       * <pre>
       * rotate 90 degrees counterclockwise
       * </pre>
       *
       * <code>CCW = 1;</code>
       */
      public static final int CCW_VALUE = 1;
      /**
       * <pre>
       * hack to rectify convfloat
       * </pre>
       *
       * <code>CCW_FLIP = 2;</code>
       */
      public static final int CCW_FLIP_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Rotation valueOf(int value) {
        return forNumber(value);
      }

      public static Rotation forNumber(int value) {
        switch (value) {
          case 0: return NONE;
          case 1: return CCW;
          case 2: return CCW_FLIP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Rotation>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Rotation> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Rotation>() {
              public Rotation findValueByNumber(int number) {
                return Rotation.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return mediapipe.CopyCalculator.CopyCalculatorOptions.getDescriptor().getEnumTypes().get(0);
      }

      private static final Rotation[] VALUES = values();

      public static Rotation valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Rotation(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:mediapipe.CopyCalculatorOptions.Rotation)
    }

    private int bitField0_;
    public static final int ROTATION_FIELD_NUMBER = 1;
    private int rotation_;
    /**
     * <code>optional .mediapipe.CopyCalculatorOptions.Rotation rotation = 1 [default = NONE];</code>
     */
    public boolean hasRotation() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .mediapipe.CopyCalculatorOptions.Rotation rotation = 1 [default = NONE];</code>
     */
    public mediapipe.CopyCalculator.CopyCalculatorOptions.Rotation getRotation() {
      mediapipe.CopyCalculator.CopyCalculatorOptions.Rotation result = mediapipe.CopyCalculator.CopyCalculatorOptions.Rotation.valueOf(rotation_);
      return result == null ? mediapipe.CopyCalculator.CopyCalculatorOptions.Rotation.NONE : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, rotation_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, rotation_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mediapipe.CopyCalculator.CopyCalculatorOptions)) {
        return super.equals(obj);
      }
      mediapipe.CopyCalculator.CopyCalculatorOptions other = (mediapipe.CopyCalculator.CopyCalculatorOptions) obj;

      boolean result = true;
      result = result && (hasRotation() == other.hasRotation());
      if (hasRotation()) {
        result = result && rotation_ == other.rotation_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasRotation()) {
        hash = (37 * hash) + ROTATION_FIELD_NUMBER;
        hash = (53 * hash) + rotation_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mediapipe.CopyCalculator.CopyCalculatorOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mediapipe.CopyCalculator.CopyCalculatorOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mediapipe.CopyCalculator.CopyCalculatorOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mediapipe.CopyCalculator.CopyCalculatorOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mediapipe.CopyCalculator.CopyCalculatorOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mediapipe.CopyCalculator.CopyCalculatorOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mediapipe.CopyCalculator.CopyCalculatorOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mediapipe.CopyCalculator.CopyCalculatorOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mediapipe.CopyCalculator.CopyCalculatorOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mediapipe.CopyCalculator.CopyCalculatorOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mediapipe.CopyCalculator.CopyCalculatorOptions prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mediapipe.CopyCalculatorOptions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mediapipe.CopyCalculatorOptions)
        mediapipe.CopyCalculator.CopyCalculatorOptionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mediapipe.CopyCalculator.internal_static_mediapipe_CopyCalculatorOptions_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mediapipe.CopyCalculator.internal_static_mediapipe_CopyCalculatorOptions_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mediapipe.CopyCalculator.CopyCalculatorOptions.class, mediapipe.CopyCalculator.CopyCalculatorOptions.Builder.class);
      }

      // Construct using mediapipe.CopyCalculator.CopyCalculatorOptions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        rotation_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mediapipe.CopyCalculator.internal_static_mediapipe_CopyCalculatorOptions_descriptor;
      }

      public mediapipe.CopyCalculator.CopyCalculatorOptions getDefaultInstanceForType() {
        return mediapipe.CopyCalculator.CopyCalculatorOptions.getDefaultInstance();
      }

      public mediapipe.CopyCalculator.CopyCalculatorOptions build() {
        mediapipe.CopyCalculator.CopyCalculatorOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public mediapipe.CopyCalculator.CopyCalculatorOptions buildPartial() {
        mediapipe.CopyCalculator.CopyCalculatorOptions result = new mediapipe.CopyCalculator.CopyCalculatorOptions(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rotation_ = rotation_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mediapipe.CopyCalculator.CopyCalculatorOptions) {
          return mergeFrom((mediapipe.CopyCalculator.CopyCalculatorOptions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mediapipe.CopyCalculator.CopyCalculatorOptions other) {
        if (other == mediapipe.CopyCalculator.CopyCalculatorOptions.getDefaultInstance()) return this;
        if (other.hasRotation()) {
          setRotation(other.getRotation());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mediapipe.CopyCalculator.CopyCalculatorOptions parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mediapipe.CopyCalculator.CopyCalculatorOptions) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int rotation_ = 0;
      /**
       * <code>optional .mediapipe.CopyCalculatorOptions.Rotation rotation = 1 [default = NONE];</code>
       */
      public boolean hasRotation() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .mediapipe.CopyCalculatorOptions.Rotation rotation = 1 [default = NONE];</code>
       */
      public mediapipe.CopyCalculator.CopyCalculatorOptions.Rotation getRotation() {
        mediapipe.CopyCalculator.CopyCalculatorOptions.Rotation result = mediapipe.CopyCalculator.CopyCalculatorOptions.Rotation.valueOf(rotation_);
        return result == null ? mediapipe.CopyCalculator.CopyCalculatorOptions.Rotation.NONE : result;
      }
      /**
       * <code>optional .mediapipe.CopyCalculatorOptions.Rotation rotation = 1 [default = NONE];</code>
       */
      public Builder setRotation(mediapipe.CopyCalculator.CopyCalculatorOptions.Rotation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        rotation_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .mediapipe.CopyCalculatorOptions.Rotation rotation = 1 [default = NONE];</code>
       */
      public Builder clearRotation() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rotation_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mediapipe.CopyCalculatorOptions)
    }

    // @@protoc_insertion_point(class_scope:mediapipe.CopyCalculatorOptions)
    private static final mediapipe.CopyCalculator.CopyCalculatorOptions DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mediapipe.CopyCalculator.CopyCalculatorOptions();
    }

    public static mediapipe.CopyCalculator.CopyCalculatorOptions getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CopyCalculatorOptions>
        PARSER = new com.google.protobuf.AbstractParser<CopyCalculatorOptions>() {
      public CopyCalculatorOptions parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CopyCalculatorOptions(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CopyCalculatorOptions> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CopyCalculatorOptions> getParserForType() {
      return PARSER;
    }

    public mediapipe.CopyCalculator.CopyCalculatorOptions getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

    public static final int EXT_FIELD_NUMBER = 161773876;
    /**
     * <code>extend .mediapipe.CalculatorOptions { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.google.mediapipe.proto.CalculatorOptionsProto.CalculatorOptions,
        mediapipe.CopyCalculator.CopyCalculatorOptions> ext = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          mediapipe.CopyCalculator.CopyCalculatorOptions.getDefaultInstance(),
          0,
          mediapipe.CopyCalculator.CopyCalculatorOptions.class,
          mediapipe.CopyCalculator.CopyCalculatorOptions.getDefaultInstance());
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mediapipe_CopyCalculatorOptions_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mediapipe_CopyCalculatorOptions_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#mediapipe/gpu/copy_calculator.proto\022\tm" +
      "ediapipe\032$mediapipe/framework/calculator" +
      ".proto\"\327\001\n\025CopyCalculatorOptions\022A\n\010rota" +
      "tion\030\001 \001(\0162).mediapipe.CopyCalculatorOpt" +
      "ions.Rotation:\004NONE\"+\n\010Rotation\022\010\n\004NONE\020" +
      "\000\022\007\n\003CCW\020\001\022\014\n\010CCW_FLIP\020\0022N\n\003ext\022\034.mediap" +
      "ipe.CalculatorOptions\030\264\362\221M \001(\0132 .mediapi" +
      "pe.CopyCalculatorOptions"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.mediapipe.proto.CalculatorProto.getDescriptor(),
        }, assigner);
    internal_static_mediapipe_CopyCalculatorOptions_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mediapipe_CopyCalculatorOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mediapipe_CopyCalculatorOptions_descriptor,
        new java.lang.String[] { "Rotation", });
    com.google.mediapipe.proto.CalculatorProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
