// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mediapipe/framework/packet_test.proto

package mediapipe;

public final class PacketTest {
  private PacketTest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PacketTestProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mediapipe.PacketTestProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Tests that the tags used to encode the timestamp do not interfere with
     * proto tags.
     * </pre>
     *
     * <code>repeated int32 x = 1777;</code>
     */
    java.util.List<java.lang.Integer> getXList();
    /**
     * <pre>
     * Tests that the tags used to encode the timestamp do not interfere with
     * proto tags.
     * </pre>
     *
     * <code>repeated int32 x = 1777;</code>
     */
    int getXCount();
    /**
     * <pre>
     * Tests that the tags used to encode the timestamp do not interfere with
     * proto tags.
     * </pre>
     *
     * <code>repeated int32 x = 1777;</code>
     */
    int getX(int index);

    /**
     * <pre>
     * The tag below = 1777 | (1 &lt;&lt; 28).
     * </pre>
     *
     * <code>repeated int32 y = 268437233;</code>
     */
    java.util.List<java.lang.Integer> getYList();
    /**
     * <pre>
     * The tag below = 1777 | (1 &lt;&lt; 28).
     * </pre>
     *
     * <code>repeated int32 y = 268437233;</code>
     */
    int getYCount();
    /**
     * <pre>
     * The tag below = 1777 | (1 &lt;&lt; 28).
     * </pre>
     *
     * <code>repeated int32 y = 268437233;</code>
     */
    int getY(int index);
  }
  /**
   * Protobuf type {@code mediapipe.PacketTestProto}
   */
  public  static final class PacketTestProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mediapipe.PacketTestProto)
      PacketTestProtoOrBuilder {
    // Use PacketTestProto.newBuilder() to construct.
    private PacketTestProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PacketTestProto() {
      x_ = java.util.Collections.emptyList();
      y_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PacketTestProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 14216: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                x_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              x_.add(input.readInt32());
              break;
            }
            case 14218: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                x_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                x_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case (int) 2147497864L: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                y_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              y_.add(input.readInt32());
              break;
            }
            case (int) 2147497866L: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                y_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                y_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          x_ = java.util.Collections.unmodifiableList(x_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          y_ = java.util.Collections.unmodifiableList(y_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mediapipe.PacketTest.internal_static_mediapipe_PacketTestProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mediapipe.PacketTest.internal_static_mediapipe_PacketTestProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mediapipe.PacketTest.PacketTestProto.class, mediapipe.PacketTest.PacketTestProto.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1777;
    private java.util.List<java.lang.Integer> x_;
    /**
     * <pre>
     * Tests that the tags used to encode the timestamp do not interfere with
     * proto tags.
     * </pre>
     *
     * <code>repeated int32 x = 1777;</code>
     */
    public java.util.List<java.lang.Integer>
        getXList() {
      return x_;
    }
    /**
     * <pre>
     * Tests that the tags used to encode the timestamp do not interfere with
     * proto tags.
     * </pre>
     *
     * <code>repeated int32 x = 1777;</code>
     */
    public int getXCount() {
      return x_.size();
    }
    /**
     * <pre>
     * Tests that the tags used to encode the timestamp do not interfere with
     * proto tags.
     * </pre>
     *
     * <code>repeated int32 x = 1777;</code>
     */
    public int getX(int index) {
      return x_.get(index);
    }

    public static final int Y_FIELD_NUMBER = 268437233;
    private java.util.List<java.lang.Integer> y_;
    /**
     * <pre>
     * The tag below = 1777 | (1 &lt;&lt; 28).
     * </pre>
     *
     * <code>repeated int32 y = 268437233;</code>
     */
    public java.util.List<java.lang.Integer>
        getYList() {
      return y_;
    }
    /**
     * <pre>
     * The tag below = 1777 | (1 &lt;&lt; 28).
     * </pre>
     *
     * <code>repeated int32 y = 268437233;</code>
     */
    public int getYCount() {
      return y_.size();
    }
    /**
     * <pre>
     * The tag below = 1777 | (1 &lt;&lt; 28).
     * </pre>
     *
     * <code>repeated int32 y = 268437233;</code>
     */
    public int getY(int index) {
      return y_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < x_.size(); i++) {
        output.writeInt32(1777, x_.get(i));
      }
      for (int i = 0; i < y_.size(); i++) {
        output.writeInt32(268437233, y_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < x_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(x_.get(i));
        }
        size += dataSize;
        size += 2 * getXList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < y_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(y_.get(i));
        }
        size += dataSize;
        size += 5 * getYList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mediapipe.PacketTest.PacketTestProto)) {
        return super.equals(obj);
      }
      mediapipe.PacketTest.PacketTestProto other = (mediapipe.PacketTest.PacketTestProto) obj;

      boolean result = true;
      result = result && getXList()
          .equals(other.getXList());
      result = result && getYList()
          .equals(other.getYList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getXCount() > 0) {
        hash = (37 * hash) + X_FIELD_NUMBER;
        hash = (53 * hash) + getXList().hashCode();
      }
      if (getYCount() > 0) {
        hash = (37 * hash) + Y_FIELD_NUMBER;
        hash = (53 * hash) + getYList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mediapipe.PacketTest.PacketTestProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mediapipe.PacketTest.PacketTestProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mediapipe.PacketTest.PacketTestProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mediapipe.PacketTest.PacketTestProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mediapipe.PacketTest.PacketTestProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mediapipe.PacketTest.PacketTestProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mediapipe.PacketTest.PacketTestProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mediapipe.PacketTest.PacketTestProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mediapipe.PacketTest.PacketTestProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mediapipe.PacketTest.PacketTestProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mediapipe.PacketTest.PacketTestProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mediapipe.PacketTestProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mediapipe.PacketTestProto)
        mediapipe.PacketTest.PacketTestProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mediapipe.PacketTest.internal_static_mediapipe_PacketTestProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mediapipe.PacketTest.internal_static_mediapipe_PacketTestProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mediapipe.PacketTest.PacketTestProto.class, mediapipe.PacketTest.PacketTestProto.Builder.class);
      }

      // Construct using mediapipe.PacketTest.PacketTestProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        x_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mediapipe.PacketTest.internal_static_mediapipe_PacketTestProto_descriptor;
      }

      public mediapipe.PacketTest.PacketTestProto getDefaultInstanceForType() {
        return mediapipe.PacketTest.PacketTestProto.getDefaultInstance();
      }

      public mediapipe.PacketTest.PacketTestProto build() {
        mediapipe.PacketTest.PacketTestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public mediapipe.PacketTest.PacketTestProto buildPartial() {
        mediapipe.PacketTest.PacketTestProto result = new mediapipe.PacketTest.PacketTestProto(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          x_ = java.util.Collections.unmodifiableList(x_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.x_ = x_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          y_ = java.util.Collections.unmodifiableList(y_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.y_ = y_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mediapipe.PacketTest.PacketTestProto) {
          return mergeFrom((mediapipe.PacketTest.PacketTestProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mediapipe.PacketTest.PacketTestProto other) {
        if (other == mediapipe.PacketTest.PacketTestProto.getDefaultInstance()) return this;
        if (!other.x_.isEmpty()) {
          if (x_.isEmpty()) {
            x_ = other.x_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureXIsMutable();
            x_.addAll(other.x_);
          }
          onChanged();
        }
        if (!other.y_.isEmpty()) {
          if (y_.isEmpty()) {
            y_ = other.y_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureYIsMutable();
            y_.addAll(other.y_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mediapipe.PacketTest.PacketTestProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mediapipe.PacketTest.PacketTestProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> x_ = java.util.Collections.emptyList();
      private void ensureXIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          x_ = new java.util.ArrayList<java.lang.Integer>(x_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * Tests that the tags used to encode the timestamp do not interfere with
       * proto tags.
       * </pre>
       *
       * <code>repeated int32 x = 1777;</code>
       */
      public java.util.List<java.lang.Integer>
          getXList() {
        return java.util.Collections.unmodifiableList(x_);
      }
      /**
       * <pre>
       * Tests that the tags used to encode the timestamp do not interfere with
       * proto tags.
       * </pre>
       *
       * <code>repeated int32 x = 1777;</code>
       */
      public int getXCount() {
        return x_.size();
      }
      /**
       * <pre>
       * Tests that the tags used to encode the timestamp do not interfere with
       * proto tags.
       * </pre>
       *
       * <code>repeated int32 x = 1777;</code>
       */
      public int getX(int index) {
        return x_.get(index);
      }
      /**
       * <pre>
       * Tests that the tags used to encode the timestamp do not interfere with
       * proto tags.
       * </pre>
       *
       * <code>repeated int32 x = 1777;</code>
       */
      public Builder setX(
          int index, int value) {
        ensureXIsMutable();
        x_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Tests that the tags used to encode the timestamp do not interfere with
       * proto tags.
       * </pre>
       *
       * <code>repeated int32 x = 1777;</code>
       */
      public Builder addX(int value) {
        ensureXIsMutable();
        x_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Tests that the tags used to encode the timestamp do not interfere with
       * proto tags.
       * </pre>
       *
       * <code>repeated int32 x = 1777;</code>
       */
      public Builder addAllX(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureXIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, x_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Tests that the tags used to encode the timestamp do not interfere with
       * proto tags.
       * </pre>
       *
       * <code>repeated int32 x = 1777;</code>
       */
      public Builder clearX() {
        x_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> y_ = java.util.Collections.emptyList();
      private void ensureYIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          y_ = new java.util.ArrayList<java.lang.Integer>(y_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <pre>
       * The tag below = 1777 | (1 &lt;&lt; 28).
       * </pre>
       *
       * <code>repeated int32 y = 268437233;</code>
       */
      public java.util.List<java.lang.Integer>
          getYList() {
        return java.util.Collections.unmodifiableList(y_);
      }
      /**
       * <pre>
       * The tag below = 1777 | (1 &lt;&lt; 28).
       * </pre>
       *
       * <code>repeated int32 y = 268437233;</code>
       */
      public int getYCount() {
        return y_.size();
      }
      /**
       * <pre>
       * The tag below = 1777 | (1 &lt;&lt; 28).
       * </pre>
       *
       * <code>repeated int32 y = 268437233;</code>
       */
      public int getY(int index) {
        return y_.get(index);
      }
      /**
       * <pre>
       * The tag below = 1777 | (1 &lt;&lt; 28).
       * </pre>
       *
       * <code>repeated int32 y = 268437233;</code>
       */
      public Builder setY(
          int index, int value) {
        ensureYIsMutable();
        y_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The tag below = 1777 | (1 &lt;&lt; 28).
       * </pre>
       *
       * <code>repeated int32 y = 268437233;</code>
       */
      public Builder addY(int value) {
        ensureYIsMutable();
        y_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The tag below = 1777 | (1 &lt;&lt; 28).
       * </pre>
       *
       * <code>repeated int32 y = 268437233;</code>
       */
      public Builder addAllY(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureYIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, y_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The tag below = 1777 | (1 &lt;&lt; 28).
       * </pre>
       *
       * <code>repeated int32 y = 268437233;</code>
       */
      public Builder clearY() {
        y_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mediapipe.PacketTestProto)
    }

    // @@protoc_insertion_point(class_scope:mediapipe.PacketTestProto)
    private static final mediapipe.PacketTest.PacketTestProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mediapipe.PacketTest.PacketTestProto();
    }

    public static mediapipe.PacketTest.PacketTestProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PacketTestProto>
        PARSER = new com.google.protobuf.AbstractParser<PacketTestProto>() {
      public PacketTestProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PacketTestProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PacketTestProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PacketTestProto> getParserForType() {
      return PARSER;
    }

    public mediapipe.PacketTest.PacketTestProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SimpleProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mediapipe.SimpleProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated bytes value = 1;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getValueList();
    /**
     * <code>repeated bytes value = 1;</code>
     */
    int getValueCount();
    /**
     * <code>repeated bytes value = 1;</code>
     */
    com.google.protobuf.ByteString getValue(int index);
  }
  /**
   * <pre>
   * A proto like InputCollection::Inputs which has embedded strings
   * within it.
   * </pre>
   *
   * Protobuf type {@code mediapipe.SimpleProto}
   */
  public  static final class SimpleProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mediapipe.SimpleProto)
      SimpleProtoOrBuilder {
    // Use SimpleProto.newBuilder() to construct.
    private SimpleProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SimpleProto() {
      value_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SimpleProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                value_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              value_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          value_ = java.util.Collections.unmodifiableList(value_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mediapipe.PacketTest.internal_static_mediapipe_SimpleProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mediapipe.PacketTest.internal_static_mediapipe_SimpleProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mediapipe.PacketTest.SimpleProto.class, mediapipe.PacketTest.SimpleProto.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.ByteString> value_;
    /**
     * <code>repeated bytes value = 1;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getValueList() {
      return value_;
    }
    /**
     * <code>repeated bytes value = 1;</code>
     */
    public int getValueCount() {
      return value_.size();
    }
    /**
     * <code>repeated bytes value = 1;</code>
     */
    public com.google.protobuf.ByteString getValue(int index) {
      return value_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < value_.size(); i++) {
        output.writeBytes(1, value_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < value_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(value_.get(i));
        }
        size += dataSize;
        size += 1 * getValueList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mediapipe.PacketTest.SimpleProto)) {
        return super.equals(obj);
      }
      mediapipe.PacketTest.SimpleProto other = (mediapipe.PacketTest.SimpleProto) obj;

      boolean result = true;
      result = result && getValueList()
          .equals(other.getValueList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getValueCount() > 0) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValueList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mediapipe.PacketTest.SimpleProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mediapipe.PacketTest.SimpleProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mediapipe.PacketTest.SimpleProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mediapipe.PacketTest.SimpleProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mediapipe.PacketTest.SimpleProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mediapipe.PacketTest.SimpleProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mediapipe.PacketTest.SimpleProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mediapipe.PacketTest.SimpleProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mediapipe.PacketTest.SimpleProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mediapipe.PacketTest.SimpleProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mediapipe.PacketTest.SimpleProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * A proto like InputCollection::Inputs which has embedded strings
     * within it.
     * </pre>
     *
     * Protobuf type {@code mediapipe.SimpleProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mediapipe.SimpleProto)
        mediapipe.PacketTest.SimpleProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mediapipe.PacketTest.internal_static_mediapipe_SimpleProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mediapipe.PacketTest.internal_static_mediapipe_SimpleProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mediapipe.PacketTest.SimpleProto.class, mediapipe.PacketTest.SimpleProto.Builder.class);
      }

      // Construct using mediapipe.PacketTest.SimpleProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        value_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mediapipe.PacketTest.internal_static_mediapipe_SimpleProto_descriptor;
      }

      public mediapipe.PacketTest.SimpleProto getDefaultInstanceForType() {
        return mediapipe.PacketTest.SimpleProto.getDefaultInstance();
      }

      public mediapipe.PacketTest.SimpleProto build() {
        mediapipe.PacketTest.SimpleProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public mediapipe.PacketTest.SimpleProto buildPartial() {
        mediapipe.PacketTest.SimpleProto result = new mediapipe.PacketTest.SimpleProto(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          value_ = java.util.Collections.unmodifiableList(value_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.value_ = value_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mediapipe.PacketTest.SimpleProto) {
          return mergeFrom((mediapipe.PacketTest.SimpleProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mediapipe.PacketTest.SimpleProto other) {
        if (other == mediapipe.PacketTest.SimpleProto.getDefaultInstance()) return this;
        if (!other.value_.isEmpty()) {
          if (value_.isEmpty()) {
            value_ = other.value_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureValueIsMutable();
            value_.addAll(other.value_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mediapipe.PacketTest.SimpleProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mediapipe.PacketTest.SimpleProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.google.protobuf.ByteString> value_ = java.util.Collections.emptyList();
      private void ensureValueIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          value_ = new java.util.ArrayList<com.google.protobuf.ByteString>(value_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes value = 1;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getValueList() {
        return java.util.Collections.unmodifiableList(value_);
      }
      /**
       * <code>repeated bytes value = 1;</code>
       */
      public int getValueCount() {
        return value_.size();
      }
      /**
       * <code>repeated bytes value = 1;</code>
       */
      public com.google.protobuf.ByteString getValue(int index) {
        return value_.get(index);
      }
      /**
       * <code>repeated bytes value = 1;</code>
       */
      public Builder setValue(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValueIsMutable();
        value_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes value = 1;</code>
       */
      public Builder addValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValueIsMutable();
        value_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes value = 1;</code>
       */
      public Builder addAllValue(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureValueIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, value_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes value = 1;</code>
       */
      public Builder clearValue() {
        value_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mediapipe.SimpleProto)
    }

    // @@protoc_insertion_point(class_scope:mediapipe.SimpleProto)
    private static final mediapipe.PacketTest.SimpleProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mediapipe.PacketTest.SimpleProto();
    }

    public static mediapipe.PacketTest.SimpleProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SimpleProto>
        PARSER = new com.google.protobuf.AbstractParser<SimpleProto>() {
      public SimpleProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SimpleProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SimpleProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SimpleProto> getParserForType() {
      return PARSER;
    }

    public mediapipe.PacketTest.SimpleProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SerializationProxyProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mediapipe.SerializationProxyProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool bool_value = 1;</code>
     */
    boolean hasBoolValue();
    /**
     * <code>optional bool bool_value = 1;</code>
     */
    boolean getBoolValue();

    /**
     * <code>repeated float float_value = 2;</code>
     */
    java.util.List<java.lang.Float> getFloatValueList();
    /**
     * <code>repeated float float_value = 2;</code>
     */
    int getFloatValueCount();
    /**
     * <code>repeated float float_value = 2;</code>
     */
    float getFloatValue(int index);

    /**
     * <code>repeated string string_value = 3;</code>
     */
    java.util.List<java.lang.String>
        getStringValueList();
    /**
     * <code>repeated string string_value = 3;</code>
     */
    int getStringValueCount();
    /**
     * <code>repeated string string_value = 3;</code>
     */
    java.lang.String getStringValue(int index);
    /**
     * <code>repeated string string_value = 3;</code>
     */
    com.google.protobuf.ByteString
        getStringValueBytes(int index);
  }
  /**
   * <pre>
   * A proto that acts as the proxy of SerializationProxyTestClass for
   * serialization.
   * </pre>
   *
   * Protobuf type {@code mediapipe.SerializationProxyProto}
   */
  public  static final class SerializationProxyProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mediapipe.SerializationProxyProto)
      SerializationProxyProtoOrBuilder {
    // Use SerializationProxyProto.newBuilder() to construct.
    private SerializationProxyProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SerializationProxyProto() {
      boolValue_ = false;
      floatValue_ = java.util.Collections.emptyList();
      stringValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SerializationProxyProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              boolValue_ = input.readBool();
              break;
            }
            case 21: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                floatValue_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000002;
              }
              floatValue_.add(input.readFloat());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                floatValue_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                floatValue_.add(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                stringValue_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              stringValue_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          floatValue_ = java.util.Collections.unmodifiableList(floatValue_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          stringValue_ = stringValue_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mediapipe.PacketTest.internal_static_mediapipe_SerializationProxyProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mediapipe.PacketTest.internal_static_mediapipe_SerializationProxyProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mediapipe.PacketTest.SerializationProxyProto.class, mediapipe.PacketTest.SerializationProxyProto.Builder.class);
    }

    private int bitField0_;
    public static final int BOOL_VALUE_FIELD_NUMBER = 1;
    private boolean boolValue_;
    /**
     * <code>optional bool bool_value = 1;</code>
     */
    public boolean hasBoolValue() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool bool_value = 1;</code>
     */
    public boolean getBoolValue() {
      return boolValue_;
    }

    public static final int FLOAT_VALUE_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Float> floatValue_;
    /**
     * <code>repeated float float_value = 2;</code>
     */
    public java.util.List<java.lang.Float>
        getFloatValueList() {
      return floatValue_;
    }
    /**
     * <code>repeated float float_value = 2;</code>
     */
    public int getFloatValueCount() {
      return floatValue_.size();
    }
    /**
     * <code>repeated float float_value = 2;</code>
     */
    public float getFloatValue(int index) {
      return floatValue_.get(index);
    }

    public static final int STRING_VALUE_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList stringValue_;
    /**
     * <code>repeated string string_value = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getStringValueList() {
      return stringValue_;
    }
    /**
     * <code>repeated string string_value = 3;</code>
     */
    public int getStringValueCount() {
      return stringValue_.size();
    }
    /**
     * <code>repeated string string_value = 3;</code>
     */
    public java.lang.String getStringValue(int index) {
      return stringValue_.get(index);
    }
    /**
     * <code>repeated string string_value = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStringValueBytes(int index) {
      return stringValue_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, boolValue_);
      }
      for (int i = 0; i < floatValue_.size(); i++) {
        output.writeFloat(2, floatValue_.get(i));
      }
      for (int i = 0; i < stringValue_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, stringValue_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, boolValue_);
      }
      {
        int dataSize = 0;
        dataSize = 4 * getFloatValueList().size();
        size += dataSize;
        size += 1 * getFloatValueList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < stringValue_.size(); i++) {
          dataSize += computeStringSizeNoTag(stringValue_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getStringValueList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mediapipe.PacketTest.SerializationProxyProto)) {
        return super.equals(obj);
      }
      mediapipe.PacketTest.SerializationProxyProto other = (mediapipe.PacketTest.SerializationProxyProto) obj;

      boolean result = true;
      result = result && (hasBoolValue() == other.hasBoolValue());
      if (hasBoolValue()) {
        result = result && (getBoolValue()
            == other.getBoolValue());
      }
      result = result && getFloatValueList()
          .equals(other.getFloatValueList());
      result = result && getStringValueList()
          .equals(other.getStringValueList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasBoolValue()) {
        hash = (37 * hash) + BOOL_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getBoolValue());
      }
      if (getFloatValueCount() > 0) {
        hash = (37 * hash) + FLOAT_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getFloatValueList().hashCode();
      }
      if (getStringValueCount() > 0) {
        hash = (37 * hash) + STRING_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getStringValueList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mediapipe.PacketTest.SerializationProxyProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mediapipe.PacketTest.SerializationProxyProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mediapipe.PacketTest.SerializationProxyProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mediapipe.PacketTest.SerializationProxyProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mediapipe.PacketTest.SerializationProxyProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mediapipe.PacketTest.SerializationProxyProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mediapipe.PacketTest.SerializationProxyProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mediapipe.PacketTest.SerializationProxyProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mediapipe.PacketTest.SerializationProxyProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mediapipe.PacketTest.SerializationProxyProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mediapipe.PacketTest.SerializationProxyProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * A proto that acts as the proxy of SerializationProxyTestClass for
     * serialization.
     * </pre>
     *
     * Protobuf type {@code mediapipe.SerializationProxyProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mediapipe.SerializationProxyProto)
        mediapipe.PacketTest.SerializationProxyProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mediapipe.PacketTest.internal_static_mediapipe_SerializationProxyProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mediapipe.PacketTest.internal_static_mediapipe_SerializationProxyProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mediapipe.PacketTest.SerializationProxyProto.class, mediapipe.PacketTest.SerializationProxyProto.Builder.class);
      }

      // Construct using mediapipe.PacketTest.SerializationProxyProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        boolValue_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        floatValue_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        stringValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mediapipe.PacketTest.internal_static_mediapipe_SerializationProxyProto_descriptor;
      }

      public mediapipe.PacketTest.SerializationProxyProto getDefaultInstanceForType() {
        return mediapipe.PacketTest.SerializationProxyProto.getDefaultInstance();
      }

      public mediapipe.PacketTest.SerializationProxyProto build() {
        mediapipe.PacketTest.SerializationProxyProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public mediapipe.PacketTest.SerializationProxyProto buildPartial() {
        mediapipe.PacketTest.SerializationProxyProto result = new mediapipe.PacketTest.SerializationProxyProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.boolValue_ = boolValue_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          floatValue_ = java.util.Collections.unmodifiableList(floatValue_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.floatValue_ = floatValue_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          stringValue_ = stringValue_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.stringValue_ = stringValue_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mediapipe.PacketTest.SerializationProxyProto) {
          return mergeFrom((mediapipe.PacketTest.SerializationProxyProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mediapipe.PacketTest.SerializationProxyProto other) {
        if (other == mediapipe.PacketTest.SerializationProxyProto.getDefaultInstance()) return this;
        if (other.hasBoolValue()) {
          setBoolValue(other.getBoolValue());
        }
        if (!other.floatValue_.isEmpty()) {
          if (floatValue_.isEmpty()) {
            floatValue_ = other.floatValue_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureFloatValueIsMutable();
            floatValue_.addAll(other.floatValue_);
          }
          onChanged();
        }
        if (!other.stringValue_.isEmpty()) {
          if (stringValue_.isEmpty()) {
            stringValue_ = other.stringValue_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureStringValueIsMutable();
            stringValue_.addAll(other.stringValue_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mediapipe.PacketTest.SerializationProxyProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mediapipe.PacketTest.SerializationProxyProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean boolValue_ ;
      /**
       * <code>optional bool bool_value = 1;</code>
       */
      public boolean hasBoolValue() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool bool_value = 1;</code>
       */
      public boolean getBoolValue() {
        return boolValue_;
      }
      /**
       * <code>optional bool bool_value = 1;</code>
       */
      public Builder setBoolValue(boolean value) {
        bitField0_ |= 0x00000001;
        boolValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool bool_value = 1;</code>
       */
      public Builder clearBoolValue() {
        bitField0_ = (bitField0_ & ~0x00000001);
        boolValue_ = false;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Float> floatValue_ = java.util.Collections.emptyList();
      private void ensureFloatValueIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          floatValue_ = new java.util.ArrayList<java.lang.Float>(floatValue_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated float float_value = 2;</code>
       */
      public java.util.List<java.lang.Float>
          getFloatValueList() {
        return java.util.Collections.unmodifiableList(floatValue_);
      }
      /**
       * <code>repeated float float_value = 2;</code>
       */
      public int getFloatValueCount() {
        return floatValue_.size();
      }
      /**
       * <code>repeated float float_value = 2;</code>
       */
      public float getFloatValue(int index) {
        return floatValue_.get(index);
      }
      /**
       * <code>repeated float float_value = 2;</code>
       */
      public Builder setFloatValue(
          int index, float value) {
        ensureFloatValueIsMutable();
        floatValue_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float float_value = 2;</code>
       */
      public Builder addFloatValue(float value) {
        ensureFloatValueIsMutable();
        floatValue_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float float_value = 2;</code>
       */
      public Builder addAllFloatValue(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureFloatValueIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, floatValue_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float float_value = 2;</code>
       */
      public Builder clearFloatValue() {
        floatValue_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList stringValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureStringValueIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          stringValue_ = new com.google.protobuf.LazyStringArrayList(stringValue_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string string_value = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getStringValueList() {
        return stringValue_.getUnmodifiableView();
      }
      /**
       * <code>repeated string string_value = 3;</code>
       */
      public int getStringValueCount() {
        return stringValue_.size();
      }
      /**
       * <code>repeated string string_value = 3;</code>
       */
      public java.lang.String getStringValue(int index) {
        return stringValue_.get(index);
      }
      /**
       * <code>repeated string string_value = 3;</code>
       */
      public com.google.protobuf.ByteString
          getStringValueBytes(int index) {
        return stringValue_.getByteString(index);
      }
      /**
       * <code>repeated string string_value = 3;</code>
       */
      public Builder setStringValue(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStringValueIsMutable();
        stringValue_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string string_value = 3;</code>
       */
      public Builder addStringValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStringValueIsMutable();
        stringValue_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string string_value = 3;</code>
       */
      public Builder addAllStringValue(
          java.lang.Iterable<java.lang.String> values) {
        ensureStringValueIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, stringValue_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string string_value = 3;</code>
       */
      public Builder clearStringValue() {
        stringValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string string_value = 3;</code>
       */
      public Builder addStringValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStringValueIsMutable();
        stringValue_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mediapipe.SerializationProxyProto)
    }

    // @@protoc_insertion_point(class_scope:mediapipe.SerializationProxyProto)
    private static final mediapipe.PacketTest.SerializationProxyProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mediapipe.PacketTest.SerializationProxyProto();
    }

    public static mediapipe.PacketTest.SerializationProxyProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SerializationProxyProto>
        PARSER = new com.google.protobuf.AbstractParser<SerializationProxyProto>() {
      public SerializationProxyProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SerializationProxyProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SerializationProxyProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SerializationProxyProto> getParserForType() {
      return PARSER;
    }

    public mediapipe.PacketTest.SerializationProxyProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mediapipe_PacketTestProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mediapipe_PacketTestProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mediapipe_SimpleProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mediapipe_SimpleProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mediapipe_SerializationProxyProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mediapipe_SerializationProxyProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%mediapipe/framework/packet_test.proto\022" +
      "\tmediapipe\",\n\017PacketTestProto\022\n\n\001x\030\361\r \003(" +
      "\005\022\r\n\001y\030\361\215\200\200\001 \003(\005\"\034\n\013SimpleProto\022\r\n\005value" +
      "\030\001 \003(\014\"X\n\027SerializationProxyProto\022\022\n\nboo" +
      "l_value\030\001 \001(\010\022\023\n\013float_value\030\002 \003(\002\022\024\n\014st" +
      "ring_value\030\003 \003(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_mediapipe_PacketTestProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mediapipe_PacketTestProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mediapipe_PacketTestProto_descriptor,
        new java.lang.String[] { "X", "Y", });
    internal_static_mediapipe_SimpleProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mediapipe_SimpleProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mediapipe_SimpleProto_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_mediapipe_SerializationProxyProto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_mediapipe_SerializationProxyProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mediapipe_SerializationProxyProto_descriptor,
        new java.lang.String[] { "BoolValue", "FloatValue", "StringValue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
