// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mediapipe/framework/test_calculators.proto

package mediapipe;

public final class TestCalculators {
  private TestCalculators() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(mediapipe.TestCalculators.RandomMatrixCalculatorOptions.ext);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RandomMatrixCalculatorOptionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mediapipe.RandomMatrixCalculatorOptions)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 rows = 1;</code>
     */
    boolean hasRows();
    /**
     * <code>optional int32 rows = 1;</code>
     */
    int getRows();

    /**
     * <code>optional int32 cols = 2;</code>
     */
    boolean hasCols();
    /**
     * <code>optional int32 cols = 2;</code>
     */
    int getCols();

    /**
     * <code>optional int64 start_timestamp = 3;</code>
     */
    boolean hasStartTimestamp();
    /**
     * <code>optional int64 start_timestamp = 3;</code>
     */
    long getStartTimestamp();

    /**
     * <code>optional int64 limit_timestamp = 4;</code>
     */
    boolean hasLimitTimestamp();
    /**
     * <code>optional int64 limit_timestamp = 4;</code>
     */
    long getLimitTimestamp();

    /**
     * <code>optional int64 timestamp_step = 5;</code>
     */
    boolean hasTimestampStep();
    /**
     * <code>optional int64 timestamp_step = 5;</code>
     */
    long getTimestampStep();
  }
  /**
   * Protobuf type {@code mediapipe.RandomMatrixCalculatorOptions}
   */
  public  static final class RandomMatrixCalculatorOptions extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mediapipe.RandomMatrixCalculatorOptions)
      RandomMatrixCalculatorOptionsOrBuilder {
    // Use RandomMatrixCalculatorOptions.newBuilder() to construct.
    private RandomMatrixCalculatorOptions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RandomMatrixCalculatorOptions() {
      rows_ = 0;
      cols_ = 0;
      startTimestamp_ = 0L;
      limitTimestamp_ = 0L;
      timestampStep_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RandomMatrixCalculatorOptions(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              rows_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              cols_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              startTimestamp_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              limitTimestamp_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              timestampStep_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mediapipe.TestCalculators.internal_static_mediapipe_RandomMatrixCalculatorOptions_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mediapipe.TestCalculators.internal_static_mediapipe_RandomMatrixCalculatorOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mediapipe.TestCalculators.RandomMatrixCalculatorOptions.class, mediapipe.TestCalculators.RandomMatrixCalculatorOptions.Builder.class);
    }

    private int bitField0_;
    public static final int ROWS_FIELD_NUMBER = 1;
    private int rows_;
    /**
     * <code>optional int32 rows = 1;</code>
     */
    public boolean hasRows() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 rows = 1;</code>
     */
    public int getRows() {
      return rows_;
    }

    public static final int COLS_FIELD_NUMBER = 2;
    private int cols_;
    /**
     * <code>optional int32 cols = 2;</code>
     */
    public boolean hasCols() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 cols = 2;</code>
     */
    public int getCols() {
      return cols_;
    }

    public static final int START_TIMESTAMP_FIELD_NUMBER = 3;
    private long startTimestamp_;
    /**
     * <code>optional int64 start_timestamp = 3;</code>
     */
    public boolean hasStartTimestamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 start_timestamp = 3;</code>
     */
    public long getStartTimestamp() {
      return startTimestamp_;
    }

    public static final int LIMIT_TIMESTAMP_FIELD_NUMBER = 4;
    private long limitTimestamp_;
    /**
     * <code>optional int64 limit_timestamp = 4;</code>
     */
    public boolean hasLimitTimestamp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 limit_timestamp = 4;</code>
     */
    public long getLimitTimestamp() {
      return limitTimestamp_;
    }

    public static final int TIMESTAMP_STEP_FIELD_NUMBER = 5;
    private long timestampStep_;
    /**
     * <code>optional int64 timestamp_step = 5;</code>
     */
    public boolean hasTimestampStep() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 timestamp_step = 5;</code>
     */
    public long getTimestampStep() {
      return timestampStep_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, rows_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, cols_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, startTimestamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, limitTimestamp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, timestampStep_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, rows_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cols_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, startTimestamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, limitTimestamp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, timestampStep_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mediapipe.TestCalculators.RandomMatrixCalculatorOptions)) {
        return super.equals(obj);
      }
      mediapipe.TestCalculators.RandomMatrixCalculatorOptions other = (mediapipe.TestCalculators.RandomMatrixCalculatorOptions) obj;

      boolean result = true;
      result = result && (hasRows() == other.hasRows());
      if (hasRows()) {
        result = result && (getRows()
            == other.getRows());
      }
      result = result && (hasCols() == other.hasCols());
      if (hasCols()) {
        result = result && (getCols()
            == other.getCols());
      }
      result = result && (hasStartTimestamp() == other.hasStartTimestamp());
      if (hasStartTimestamp()) {
        result = result && (getStartTimestamp()
            == other.getStartTimestamp());
      }
      result = result && (hasLimitTimestamp() == other.hasLimitTimestamp());
      if (hasLimitTimestamp()) {
        result = result && (getLimitTimestamp()
            == other.getLimitTimestamp());
      }
      result = result && (hasTimestampStep() == other.hasTimestampStep());
      if (hasTimestampStep()) {
        result = result && (getTimestampStep()
            == other.getTimestampStep());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasRows()) {
        hash = (37 * hash) + ROWS_FIELD_NUMBER;
        hash = (53 * hash) + getRows();
      }
      if (hasCols()) {
        hash = (37 * hash) + COLS_FIELD_NUMBER;
        hash = (53 * hash) + getCols();
      }
      if (hasStartTimestamp()) {
        hash = (37 * hash) + START_TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getStartTimestamp());
      }
      if (hasLimitTimestamp()) {
        hash = (37 * hash) + LIMIT_TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getLimitTimestamp());
      }
      if (hasTimestampStep()) {
        hash = (37 * hash) + TIMESTAMP_STEP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimestampStep());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mediapipe.TestCalculators.RandomMatrixCalculatorOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mediapipe.TestCalculators.RandomMatrixCalculatorOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mediapipe.TestCalculators.RandomMatrixCalculatorOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mediapipe.TestCalculators.RandomMatrixCalculatorOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mediapipe.TestCalculators.RandomMatrixCalculatorOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mediapipe.TestCalculators.RandomMatrixCalculatorOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mediapipe.TestCalculators.RandomMatrixCalculatorOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mediapipe.TestCalculators.RandomMatrixCalculatorOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mediapipe.TestCalculators.RandomMatrixCalculatorOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mediapipe.TestCalculators.RandomMatrixCalculatorOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mediapipe.TestCalculators.RandomMatrixCalculatorOptions prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mediapipe.RandomMatrixCalculatorOptions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mediapipe.RandomMatrixCalculatorOptions)
        mediapipe.TestCalculators.RandomMatrixCalculatorOptionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mediapipe.TestCalculators.internal_static_mediapipe_RandomMatrixCalculatorOptions_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mediapipe.TestCalculators.internal_static_mediapipe_RandomMatrixCalculatorOptions_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mediapipe.TestCalculators.RandomMatrixCalculatorOptions.class, mediapipe.TestCalculators.RandomMatrixCalculatorOptions.Builder.class);
      }

      // Construct using mediapipe.TestCalculators.RandomMatrixCalculatorOptions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        rows_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        cols_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        startTimestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        limitTimestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        timestampStep_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mediapipe.TestCalculators.internal_static_mediapipe_RandomMatrixCalculatorOptions_descriptor;
      }

      public mediapipe.TestCalculators.RandomMatrixCalculatorOptions getDefaultInstanceForType() {
        return mediapipe.TestCalculators.RandomMatrixCalculatorOptions.getDefaultInstance();
      }

      public mediapipe.TestCalculators.RandomMatrixCalculatorOptions build() {
        mediapipe.TestCalculators.RandomMatrixCalculatorOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public mediapipe.TestCalculators.RandomMatrixCalculatorOptions buildPartial() {
        mediapipe.TestCalculators.RandomMatrixCalculatorOptions result = new mediapipe.TestCalculators.RandomMatrixCalculatorOptions(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rows_ = rows_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cols_ = cols_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.startTimestamp_ = startTimestamp_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.limitTimestamp_ = limitTimestamp_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.timestampStep_ = timestampStep_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mediapipe.TestCalculators.RandomMatrixCalculatorOptions) {
          return mergeFrom((mediapipe.TestCalculators.RandomMatrixCalculatorOptions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mediapipe.TestCalculators.RandomMatrixCalculatorOptions other) {
        if (other == mediapipe.TestCalculators.RandomMatrixCalculatorOptions.getDefaultInstance()) return this;
        if (other.hasRows()) {
          setRows(other.getRows());
        }
        if (other.hasCols()) {
          setCols(other.getCols());
        }
        if (other.hasStartTimestamp()) {
          setStartTimestamp(other.getStartTimestamp());
        }
        if (other.hasLimitTimestamp()) {
          setLimitTimestamp(other.getLimitTimestamp());
        }
        if (other.hasTimestampStep()) {
          setTimestampStep(other.getTimestampStep());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mediapipe.TestCalculators.RandomMatrixCalculatorOptions parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mediapipe.TestCalculators.RandomMatrixCalculatorOptions) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int rows_ ;
      /**
       * <code>optional int32 rows = 1;</code>
       */
      public boolean hasRows() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 rows = 1;</code>
       */
      public int getRows() {
        return rows_;
      }
      /**
       * <code>optional int32 rows = 1;</code>
       */
      public Builder setRows(int value) {
        bitField0_ |= 0x00000001;
        rows_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 rows = 1;</code>
       */
      public Builder clearRows() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rows_ = 0;
        onChanged();
        return this;
      }

      private int cols_ ;
      /**
       * <code>optional int32 cols = 2;</code>
       */
      public boolean hasCols() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 cols = 2;</code>
       */
      public int getCols() {
        return cols_;
      }
      /**
       * <code>optional int32 cols = 2;</code>
       */
      public Builder setCols(int value) {
        bitField0_ |= 0x00000002;
        cols_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cols = 2;</code>
       */
      public Builder clearCols() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cols_ = 0;
        onChanged();
        return this;
      }

      private long startTimestamp_ ;
      /**
       * <code>optional int64 start_timestamp = 3;</code>
       */
      public boolean hasStartTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 start_timestamp = 3;</code>
       */
      public long getStartTimestamp() {
        return startTimestamp_;
      }
      /**
       * <code>optional int64 start_timestamp = 3;</code>
       */
      public Builder setStartTimestamp(long value) {
        bitField0_ |= 0x00000004;
        startTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 start_timestamp = 3;</code>
       */
      public Builder clearStartTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        startTimestamp_ = 0L;
        onChanged();
        return this;
      }

      private long limitTimestamp_ ;
      /**
       * <code>optional int64 limit_timestamp = 4;</code>
       */
      public boolean hasLimitTimestamp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 limit_timestamp = 4;</code>
       */
      public long getLimitTimestamp() {
        return limitTimestamp_;
      }
      /**
       * <code>optional int64 limit_timestamp = 4;</code>
       */
      public Builder setLimitTimestamp(long value) {
        bitField0_ |= 0x00000008;
        limitTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 limit_timestamp = 4;</code>
       */
      public Builder clearLimitTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        limitTimestamp_ = 0L;
        onChanged();
        return this;
      }

      private long timestampStep_ ;
      /**
       * <code>optional int64 timestamp_step = 5;</code>
       */
      public boolean hasTimestampStep() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 timestamp_step = 5;</code>
       */
      public long getTimestampStep() {
        return timestampStep_;
      }
      /**
       * <code>optional int64 timestamp_step = 5;</code>
       */
      public Builder setTimestampStep(long value) {
        bitField0_ |= 0x00000010;
        timestampStep_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timestamp_step = 5;</code>
       */
      public Builder clearTimestampStep() {
        bitField0_ = (bitField0_ & ~0x00000010);
        timestampStep_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mediapipe.RandomMatrixCalculatorOptions)
    }

    // @@protoc_insertion_point(class_scope:mediapipe.RandomMatrixCalculatorOptions)
    private static final mediapipe.TestCalculators.RandomMatrixCalculatorOptions DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mediapipe.TestCalculators.RandomMatrixCalculatorOptions();
    }

    public static mediapipe.TestCalculators.RandomMatrixCalculatorOptions getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<RandomMatrixCalculatorOptions>
        PARSER = new com.google.protobuf.AbstractParser<RandomMatrixCalculatorOptions>() {
      public RandomMatrixCalculatorOptions parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RandomMatrixCalculatorOptions(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RandomMatrixCalculatorOptions> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RandomMatrixCalculatorOptions> getParserForType() {
      return PARSER;
    }

    public mediapipe.TestCalculators.RandomMatrixCalculatorOptions getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

    public static final int EXT_FIELD_NUMBER = 52056136;
    /**
     * <code>extend .mediapipe.CalculatorOptions { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.google.mediapipe.proto.CalculatorOptionsProto.CalculatorOptions,
        mediapipe.TestCalculators.RandomMatrixCalculatorOptions> ext = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          mediapipe.TestCalculators.RandomMatrixCalculatorOptions.getDefaultInstance(),
          0,
          mediapipe.TestCalculators.RandomMatrixCalculatorOptions.class,
          mediapipe.TestCalculators.RandomMatrixCalculatorOptions.getDefaultInstance());
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mediapipe_RandomMatrixCalculatorOptions_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mediapipe_RandomMatrixCalculatorOptions_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*mediapipe/framework/test_calculators.p" +
      "roto\022\tmediapipe\032$mediapipe/framework/cal" +
      "culator.proto\"\335\001\n\035RandomMatrixCalculator" +
      "Options\022\014\n\004rows\030\001 \001(\005\022\014\n\004cols\030\002 \001(\005\022\027\n\017s" +
      "tart_timestamp\030\003 \001(\003\022\027\n\017limit_timestamp\030" +
      "\004 \001(\003\022\026\n\016timestamp_step\030\005 \001(\0032V\n\003ext\022\034.m" +
      "ediapipe.CalculatorOptions\030\310\240\351\030 \001(\0132(.me" +
      "diapipe.RandomMatrixCalculatorOptions"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.mediapipe.proto.CalculatorProto.getDescriptor(),
        }, assigner);
    internal_static_mediapipe_RandomMatrixCalculatorOptions_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mediapipe_RandomMatrixCalculatorOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mediapipe_RandomMatrixCalculatorOptions_descriptor,
        new java.lang.String[] { "Rows", "Cols", "StartTimestamp", "LimitTimestamp", "TimestampStep", });
    com.google.mediapipe.proto.CalculatorProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
