package(default_visibility = ["//mediapipe/tasks:internal"])

licenses(["notice"])

objc_library(
    name = "MPPImageTestUtils",
    srcs = ["sources/MPPImage+TestUtils.m"],
    hdrs = ["sources/MPPImage+TestUtils.h"],
    module_name = "MPPImageTestUtils",
    deps = ["//mediapipe/tasks/ios/vision/core:MPPImage"],
)
