# This package contains options shared by all MediaPipe Texxt Tasks for Web.

load("//mediapipe/framework/port:build_config.bzl", "mediapipe_ts_declaration")

package(default_visibility = ["//mediapipe/tasks:internal"])

mediapipe_ts_declaration(
    name = "text_task_options",
    srcs = ["text_task_options.d.ts"],
    deps = ["//mediapipe/tasks/web/core"],
)
