package(default_visibility = ["//mediapipe/tasks:internal"])

licenses(["notice"])

objc_library(
    name = "MPPFileInfo",
    srcs = ["sources/MPPFileInfo.m"],
    hdrs = ["sources/MPPFileInfo.h"],
    module_name = "MPPFileInfo",
)
