# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/copper-labs/CocoaSpecs.git'

target 'PoseTrackingLindera' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'LinderaDetection' #, :path => 'LinderaDetection'

  # Pods for PoseTrackingLindera

end
