name: Model Maker Issues
description: Use this template for assistance with using MediaPipe Model Maker (developers.google.com/mediapipe/solutions) to create custom on-device ML solutions.
labels: 'type:modelmaker'
body:
  - type: markdown
    id: linkmodel
    attributes:
      value: Please make sure that this is a [Model Maker](https://developers.google.com/mediapipe/solutions) issue
  - type: dropdown
    id: customcode_model
    attributes:
      label: Have I written custom code (as opposed to using a stock example script provided in MediaPipe)
      options:
        - 'Yes'
        - 'No'
    validations:
      required: false
  - type: input
    id: os_model
    attributes:
      label: OS Platform and Distribution
      placeholder: e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4
    validations:
      required: true
  - type: input
    id: pythonver
    attributes:
      label: Python Version
      placeholder: e.g. 3.7, 3.8
    validations:
      required: true
  - type: input
    id: modelmakerver
    attributes:
      label: MediaPipe Model Maker version
    validations:
      required: false
  - type: input
    id: taskname
    attributes:
      label: Task name (e.g. Image classification, Gesture recognition etc.)
    validations:
      required: true
  - type: input
    id: current_model
    attributes:
      label: Describe the actual behavior
    validations:
      required: true
  - type: input
    id: expected_model
    attributes:
      label: Describe the expected behaviour
    validations:
      required: true
  - type: textarea
    id: what-happened_model
    attributes:
      label: Standalone code/steps you may have used to try to get what you need
      description: If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab, GitHub repo link or anything that we can use to reproduce the problem
      render: shell
    validations:
       required: true
  - type: textarea
    id: other_info
    attributes:
      label: Other info / Complete Logs
      description: Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached
      render: shell
    validations:
      required: false
