# Copyright 2025 The MediaPipe Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Stub targets for open-source builds. The internal analytics package is not
# available in the open-source repository.

load("//mediapipe/framework/port:build_config.bzl", "mediapipe_proto_library")

package(default_visibility = ["//visibility:public"])

mediapipe_proto_library(
    name = "mediapipe_logging_enums_proto",
    srcs = ["mediapipe_logging_enums.proto"],
)

mediapipe_proto_library(
    name = "mediapipe_log_extension_proto",
    srcs = ["mediapipe_log_extension.proto"],
)
