# MediaPipe graph to detect faces. (GPU input and inference.)
#
# EXAMPLE:
#   node {
#     calculator: "FaceDetectionShortRangeGpu"
#     input_stream: "IMAGE:image"
#     output_stream: "DETECTIONS:face_detections"
#   }
type: "FaceDetectionShortRangeGpu"

# The input image, either GpuBuffer, or (multi-backend) Image.
input_stream: "IMAGE:image"

# Detected faces. (std::vector<Detection>)
output_stream: "DETECTIONS:detections"

graph_options: {
  [type.googleapis.com/mediapipe.FaceDetectionOptions] {}
}

node {
  calculator: "FaceDetectionShortRange"
  input_stream: "IMAGE:image"
  output_stream: "DETECTIONS:detections"
  node_options: {
    [type.googleapis.com/mediapipe.FaceDetectionOptions] {
      gpu_origin: TOP_LEFT
      delegate: { gpu { use_advanced_gpu_api: true } }
    }
  }
  option_value: "OPTIONS:options"
}
