# MediaPipe graph that performs hair segmentation with TensorFlow Lite on GPU.
# Used in the example in
# mediapipie/examples/android/src/java/com/mediapipe/apps/hairsegmentationgpu.

# Images on GPU coming into and out of the graph.
input_stream: "input_video"
output_stream: "output_video"


node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:output_video"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

# Defines side packets for further use in the graph.
node {
  calculator: "ConstantSidePacketCalculator"
  output_side_packet: "PACKET:with_attention"
  node_options: {
    [type.googleapis.com/mediapipe.ConstantSidePacketCalculatorOptions]: {
      packet { bool_value: true }
    }
  }
}

# Defines side packets for further use in the graph.
node {
  calculator: "GpuBufferToImageFrameCalculator"
  input_stream: "throttled_input_video"
  output_stream: "throttled_input_video_cpu"
}

node {
  calculator: "ImagePropertiesCalculator"
  input_stream: "IMAGE_CPU:throttled_input_video_cpu"
  output_stream: "SIZE:original_size"
}

# Subgraph that detects faces and corresponding landmarks.
node {
  calculator: "FaceLandmarkFrontGpu"
  input_stream: "IMAGE:throttled_input_video"
  input_side_packet: "WITH_ATTENTION:with_attention"
  output_stream: "LANDMARKS:multi_face_landmarks"
}

node {
  calculator: "FastUtilsCalculator"
  input_stream: "NORM_LANDMARKS:multi_face_landmarks"
  input_stream: "IMAGE:throttled_input_video_cpu"
  input_stream: "SIZE:original_size"
  output_stream: "IMAGE:out_image_frame"
  output_stream: "LM_MASK:lm_mask"
   options {
     [mediapipe.FastUtilsCalculatorOptions.ext] {
       back_to_image: false
     }
   }
}

node: {
  calculator: "ImageTransformationCalculator"
  input_stream: "IMAGE:out_image_frame"
  output_stream: "IMAGE:image_frame"
  node_options: {
    [type.googleapis.com/mediapipe.ImageTransformationCalculatorOptions] {
      output_width: 256
      output_height: 256
    }
  }
}


node {
   calculator: "TensorConverterCalculator"
   input_stream: "IMAGE:image_frame"
   output_stream: "TENSORS:input_tensor"
   options: {
     [mediapipe.TensorConverterCalculatorOptions.ext] {
       zero_center: true
     }
   }
}

node {
  calculator: "InferenceCalculator"
  input_stream: "TENSORS:input_tensor"
  output_stream: "TENSORS:output_tensor"
  options: {
    [mediapipe.InferenceCalculatorOptions.ext] {
     model_path:"mediapipe/models/model_float32.tflite"
      delegate { gpu {} }
    }
  }
}

node {
  calculator: "TensorsToImageCalculator"
  input_stream: "TENSORS:output_tensor"
  output_stream: "IMAGE:fake_image"
}

node: {
  calculator: "FromImageCalculator"
  input_stream: "IMAGE:fake_image"
  output_stream: "IMAGE_CPU:cpu_fake_image"
}

node: {
  calculator: "ImageTransformationCalculator"
  input_stream: "IMAGE:throttled_input_video_cpu"
  output_stream: "IMAGE:transformed_input_img"
  node_options: {
    [type.googleapis.com/mediapipe.ImageTransformationCalculatorOptions] {
      output_width: 256
      output_height: 256
    }
  }
}

node {
   calculator: "TensorConverterCalculator"
   input_stream: "IMAGE:transformed_input_img"
   output_stream: "TENSORS:input_tensor_img"
   options: {
     [mediapipe.TensorConverterCalculatorOptions.ext] {
       zero_center: true
     }
   }
}

node {
  calculator: "InferenceCalculator"
  input_stream: "TENSORS:input_tensor_img"
  output_stream: "TENSORS:output_tensor_img"
  options: {
    [mediapipe.InferenceCalculatorOptions.ext] {
      model_path: "mediapipe/models/model_float32.tflite"
      delegate { xnnpack {} }
    }
  }
}


node {
  calculator: "ImagePropertiesCalculator"
  input_stream: "IMAGE_CPU:transformed_input_img"
  output_stream: "SIZE:input_size_img"
}

node {
  calculator: "TensorsToImageCalculator"
  input_stream: "TENSORS:output_tensor_img"
  input_stream: "OUTPUT_SIZE:input_size_img"
  output_stream: "IMAGE:fake_bg2"
}

node{
  calculator: "FromImageCalculator"
  input_stream: "IMAGE:fake_bg2"
  output_stream: "IMAGE_CPU:fake_bg"
}

node {
  calculator: "FastUtilsCalculator"
  input_stream: "NORM_LANDMARKS:multi_face_landmarks"
  input_stream: "IMAGE:cpu_fake_image"
  input_stream: "SIZE:original_size"
  output_stream: "IMAGE:back_image"
   options {
     [mediapipe.FastUtilsCalculatorOptions.ext] {
       back_to_image: true
     }
   }
}

node {
  calculator: "ApplyMaskCalculator"
  input_stream: "IMAGE:back_image"
  input_stream: "FAKE_BG:fake_bg"
  input_stream: "LM_MASK:lm_mask"
  output_stream: "IMAGE:out_image"
}

# Defines side packets for further use in the graph.
node {
  calculator: "ImageFrameToGpuBufferCalculator"
  input_stream: "out_image"
  output_stream: "output_video"
}
