// Copyright 2023 The MediaPipe Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#import <Foundation/Foundation.h>
#import "mediapipe/tasks/ios/components/containers/sources/MPPLandmark.h"
#import "mediapipe/tasks/ios/core/sources/MPPTaskResult.h"
#import "mediapipe/tasks/ios/vision/core/sources/MPPMask.h"

NS_ASSUME_NONNULL_BEGIN

/** Represents the pose landmarker results generated by MPPPoseLandmarker. */
NS_SWIFT_NAME(PoseLandmarkerResult)
@interface MPPPoseLandmarkerResult : MPPTaskResult

/** Pose landmarks of detected poses. */
@property(nonatomic, readonly) NSArray<NSArray<MPPNormalizedLandmark *> *> *landmarks;

/** Pose landmarks in world coordniates of detected poses. */
@property(nonatomic, readonly) NSArray<NSArray<MPPLandmark *> *> *worldLandmarks;

/**
 * An optional array of `MPPMask` objects. Each `MPPMask` in the array holds a 32 bit float array of
 * size `image width` * `image height` which represents the confidence mask for each category. Each
 * element of the float array represents the confidence with which the model predicted that the
 * corresponding pixel belongs to the category that the mask represents, usually in the range [0,1].
 * Segmentation masks for pose.
 */
@property(nonatomic, readonly, nullable) NSArray<MPPMask *> *segmentationMasks;

/**
 * Initializes a new `MPPPoseLandmarkerResult` with the given landmarks, world landmarks,
 * poseedness and timestamp (in milliseconds).
 *
 * @param landmarks The pose landmarks of detected poses.
 * @param worldLandmarks The pose landmarks in world coordniates of detected poses.
 * @param segmentationMasks The segmentationMasks of detected poses.
 * @param timestampInMilliseconds The timestamp for this result.
 *
 * @return An instance of `MPPGPoseLandmarkerResult` initialized with the given landmarks, world
 * landmarks, poseedness and timestamp (in milliseconds).
 *
 */
- (instancetype)initWithLandmarks:(NSArray<NSArray<MPPNormalizedLandmark *> *> *)landmarks
                   worldLandmarks:(NSArray<NSArray<MPPLandmark *> *> *)worldLandmarks
                segmentationMasks:(nullable NSArray<MPPMask *> *)segmentationMasks
          timestampInMilliseconds:(NSInteger)timestampInMilliseconds;

@end

NS_ASSUME_NONNULL_END
