load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mp_object_detection_aar",
    calculators = ["//mediapipe/graphs/object_detection:mobile_calculators"],
)
