load("@mediapipe//mediapipe/framework/port:build_config.bzl", "mediapipe_cc_proto_library", "mediapipe_proto_library")
package(default_visibility = ["//visibility:public"])


filegroup(
    name = "graphs",
    srcs = glob(["examples/*.pbtxt"])
)

filegroup(
    name = "task_graphs",
    srcs = glob(["**/*.pbtxt"])
)
