package(default_visibility = ["//visibility:public"])

licenses(["notice"])

cc_library(
    name = "loopback",
    hdrs = ["loopback.h"],
    deps = [
        "//mediapipe/calculators/core:previous_loopback_calculator",
        "//mediapipe/framework/api2:builder",
        "//mediapipe/framework/api2:port",
    ],
    alwayslink = 1,
)
