// Copyright 2024 The MediaPipe Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#import <Foundation/Foundation.h>
#import "mediapipe/tasks/ios/components/containers/sources/MPPClassificationResult.h"
#import "mediapipe/tasks/ios/core/sources/MPPTaskResult.h"

NS_ASSUME_NONNULL_BEGIN

/** Represents the classification results generated by `AudioClassifier`. **/
NS_SWIFT_NAME(AudioClassifierResult)
@interface MPPAudioClassifierResult : MPPTaskResult

/**
 * A list of timestamped `ClassificationResult` objects, each containing one set of results per
 * classifier head. In the "audio stream" mode, the list only contains one element, representing the
 * classification result of the audio block that starts at
 * ClassificationResult.timestampInMilliseconds in the audio stream. Otherwise, in the "audio clips"
 * mode, the list may include multiple `ClassificationResult` objects, each classifying an interval
 * of the entire audio clip that starts at `ClassificationResult.timestampInMilliseconds`.
 */
@property(nonatomic, readonly) NSArray<MPPClassificationResult *> *classificationResults;

/**
 * Initializes a new `AudioClassifierResult` with the given array of `ClassificationResult` objects
 * and timestamp (in milliseconds).
 *
 * @param classificationResults The array of `ClassificationResult` objects each containing one set
 * of results per classifier head.
 * @param timestampInMilliseconds The timestamp (in milliseconds) for this result.
 *
 * @return An instance of `AudioClassifierResult` initialized with the given
 * `ClassificationResult` and timestamp (in milliseconds).
 */
- (instancetype)initWithClassificationResult:
                    (NSArray<MPPClassificationResult *> *)classificationResults
                     timestampInMilliseconds:(NSInteger)timestampInMilliseconds;

@end

NS_ASSUME_NONNULL_END
