# MediaPipe graph to load a selected selfie segmentation TF Lite model.

type: "SelfieSegmentationModelLoader"

# model_selection is an integer.
# Use 0 to select a general-purpose model (operating on a 256x256 tensor).
# Use 1 to select a model (operating on a 256x144 tensor) more optimized for
# landscape images.
#
# If unspecified, 0 is selected by default.
input_side_packet: "MODEL_SELECTION:model_selection"

# TF Lite model represented as a FlatBuffer.
# (std::unique_ptr<tflite::FlatBufferModel, std::function<void(tflite::FlatBufferModel*)>>)
output_side_packet: "MODEL:model"

# Determines path to the desired pose landmark model file.
node {
  calculator: "SwitchContainer"
  input_side_packet: "SELECT:model_selection"
  output_side_packet: "PACKET:model_path"
  options: {
    [mediapipe.SwitchContainerOptions.ext] {
      select: 0
      contained_node: {
        calculator: "ConstantSidePacketCalculator"
        options: {
          [mediapipe.ConstantSidePacketCalculatorOptions.ext]: {
            packet {
              string_value: "mediapipe/modules/selfie_segmentation/selfie_segmentation.tflite"
            }
          }
        }
      }
      contained_node: {
        calculator: "ConstantSidePacketCalculator"
        options: {
          [mediapipe.ConstantSidePacketCalculatorOptions.ext]: {
            packet {
              string_value: "mediapipe/modules/selfie_segmentation/selfie_segmentation_landscape.tflite"
            }
          }
        }
      }
      #
    }
  }
}

# Loads the file in the specified path as a resource.
node {
  calculator: "ResourceProviderCalculator"
  input_side_packet: "RESOURCE_ID:model_path"
  output_side_packet: "RESOURCE:model_resource"
}

# Converts the provided resource into a TF Lite model.
node {
  calculator: "TfLiteModelCalculator"
  input_side_packet: "MODEL_RESOURCE:model_resource"
  output_side_packet: "MODEL:model"
}
