# Placeholder for internal Python strict library and test compatibility macro.
# Placeholder for internal Python strict test compatibility macro.

package(default_visibility = ["//visibility:private"])

py_library(
    name = "quantization_util",
    srcs = ["quantization_util.py"],
)

py_test(
    name = "quantization_util_test",
    srcs = ["quantization_util_test.py"],
    srcs_version = "PY3",
    deps = [
        ":quantization_util",
    ],
)
