# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'MediaPipeTasksDocGen' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MediaPipeTasksDocGen
  pod 'MediaPipeTasksText'
  pod 'MediaPipeTasksVision'
end
