# MediaPipe graph that performs hair segmentation with TensorFlow Lite on GPU.
# Used in the example in
# mediapipie/examples/android/src/java/com/mediapipe/apps/hairsegmentationgpu.

# Images on GPU coming into and out of the graph.
input_stream: "input_video"
output_stream: "output_video"


node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:output_video"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

# Defines side packets for further use in the graph.
node {
  calculator: "ConstantSidePacketCalculator"
  output_side_packet: "PACKET:with_attention"
  node_options: {
    [type.googleapis.com/mediapipe.ConstantSidePacketCalculatorOptions]: {
      packet { bool_value: true }
    }
  }
}

# Defines side packets for further use in the graph.
node {
  calculator: "GpuBufferToImageFrameCalculator"
  input_stream: "throttled_input_video"
  output_stream: "throttled_input_video_cpu"
}

# Subgraph that detects faces and corresponding landmarks.
node {
  calculator: "FaceLandmarkFrontGpu"
  input_stream: "IMAGE:throttled_input_video"
  input_side_packet: "WITH_ATTENTION:with_attention"
  output_stream: "LANDMARKS:multi_face_landmarks"
}

node {
  calculator: "ColorConvertCalculator"
  input_stream: "RGBA_IN:throttled_input_video_cpu"
  output_stream: "BGR_OUT:throttled_input_video_bgr"
}

node {
  calculator: "ImagePropertiesCalculator"
  input_stream: "IMAGE_GPU:throttled_input_video"
  output_stream: "SIZE:size"	
}

node {
   calculator: "LocalFileContentsCalculator"
   input_side_packet: "FILE_PATH:0:file_path1"
   input_side_packet: "FILE_PATH:1:file_path2"
  input_side_packet: "FILE_PATH:1:file_path2"
   output_side_packet: "CONTENTS:0:contents1"
   output_side_packet: "CONTENTS:1:contents2"
   output_side_packet: "CONTENTS:1:contents2"
}

node {
  calculator: "FaceProcessorCalculator"
  input_stream: "NORM_LANDMARKS:multi_face_landmarks"
  input_stream: "SIZE:size"
  output_stream: "SRC_TENSOR:src"
  output_stream: "DST_TENSOR:dst"
}

node {
  calculator: "WarpAffineCalculator"
  input_stream: "IMAGE:throttled_input_video_bgr"
  input_stream: "SRC_TENSOR:src"
  input_stream: "DST_TENSOR:dst"
  output_stream: "IMAGE:output_video_bgr"
}

node{
  calculator: "ColorConvertCalculator"
  input_stream: "BGR_IN:output_video_bgr"
  output_stream: "RGBA_OUT:output_video_cpu"
}

# Defines side packets for further use in the graph.
node {
  calculator: "ImageFrameToGpuBufferCalculator"
  input_stream: "output_video_cpu"
  output_stream: "output_video"
}
