#ifndef MEDIAPIPE_FRAMEWORK_PORT_COMPILE_TIME_STRING_H_
#define MEDIAPIPE_FRAMEWORK_PORT_COMPILE_TIME_STRING_H_

#include "mediapipe/framework/deps/compile_time_string.h"

#endif  // MEDIAPIPE_FRAMEWORK_PORT_COMPILE_TIME_STRING_H_
