# Copyright 2019 The MediaPipe Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load(
    "//mediapipe/framework/tool:mediapipe_files.bzl",
    "mediapipe_files",
)

licenses(["notice"])

package(default_visibility = ["//visibility:public"])

mediapipe_files(
    srcs = [
        "README.md",
        "hair_segmentation.tflite",
        "knift_float.tflite",
        "knift_float_1k.tflite",
        "knift_float_400.tflite",
        "knift_index.pb",
        "knift_labelmap.txt",
        "object_detection_saved_model/README.md",
        "object_detection_saved_model/model.ckpt.data-00000-of-00001",
        "object_detection_saved_model/model.ckpt.index",
        "object_detection_saved_model/model.ckpt.meta",
        "object_detection_saved_model/pipeline.config",
        "object_detection_saved_model/saved_model.pb",
        "ssdlite_object_detection.tflite",
        "ssdlite_object_detection_labelmap.txt",
    ],
)
